image: johngrimes/node-now
pipelines:
  default:
    - step:
        name: Run tests
        caches:
          - node
        script:
          - yarn
          - yarn test-ci
  branches:
    master:
      - step:
          name: Run tests and deploy
          caches:
            - node
          script:
            - yarn
            - yarn test-ci
            - >
              echo "{ \"fhirServer\": \"$FHIR_SERVER\" }" > public/config.json
            - yarn build
            - yarn build-docker
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            - docker push johngrimes/polecat
            - now -n polecat -t $NOW_TOKEN build
options:
  docker: true
