image: node:latest
pipelines:
  default:
    - step:
        name: Run tests
        caches:
          - node
        script:
          - yarn
          - yarn test-ci
    - step:
        name: Build Docker image
        caches:
          - node
        script:
          - yarn
          - yarn build
          - docker build . -t johngrimes/polecat
          - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          - docker push johngrimes/polecat
options:
  docker: true
