image: johngrimes/node-now
pipelines:
  default:
    - step:
        name: Run tests
        caches:
          - node
        script:
          - yarn install
          - yarn test-ci
  branches:
    master:
      - step:
          name: Run tests and deploy
          caches:
            - node
          script:
            - yarn install
            - yarn test-ci
            - yarn build
            - yarn dockerize
            - yarn push-docker
            - yarn deploy
            - yarn record-release
options:
  docker: true
