image: node:latest
pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - yarn
          - yarn test-ci
    - step:
        caches:
          - node
        script:
          - yarn
          - yarn build
          - docker build . -t johngrimes/polecat
          - docker push johngrimes/polecat
options:
  docker: true
