version: 2
jobs:
  build_and_deploy:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test-coverage
      - run: yarn codecov
      - run: yarn build
      - setup_remote_docker
      - run: yarn dockerize
      - run: yarn push-docker
      - run: ssh-keyscan $SERVER_HOSTNAME >> ~/.ssh/known_hosts
      - run: yarn deploy
      - run: yarn record-release
  build_only:
    branches:
      ignore:
        - master
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test-coverage
      - run: yarn codecov
      - run: yarn build